"""empty message

Revision ID: c9256ef483e5
Revises: 157845c58be4
Create Date: 2023-03-10 11:35:26.790548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9256ef483e5'
down_revision = '157845c58be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('discription',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('discription',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
